# Generated by Django 3.2.4 on 2021-06-23 16:13

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='TopBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_brand_logo', models.ImageField(upload_to='media/topbrandslogo')),
            ],
            options={
                'verbose_name': 'TopBrand',
                'verbose_name_plural': 'TopBrands',
            },
        ),
        migrations.CreateModel(
            name='TopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_category_icon', models.ImageField(upload_to='media/topcategoryicon')),
                ('top_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topcategories', to='store.category')),
            ],
            options={
                'verbose_name': 'TopCategory',
                'verbose_name_plural': 'TopCategories',
            },
        ),
        migrations.CreateModel(
            name='SellerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_thumbnail', models.ImageField(blank=True, null=True, upload_to='media/selleritem')),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_price', models.FloatField(default=0)),
                ('product_discount_price', models.FloatField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('flash_deal', models.BooleanField(default=False)),
                ('flash_deal_end_date', models.DateTimeField()),
                ('flash_deal_date_created', models.DateTimeField(auto_now_add=True)),
                ('most_viewed', models.BooleanField(default=False)),
                ('recommended', models.BooleanField(default=False)),
                ('deal', models.BooleanField(default=False)),
                ('deal_available_quantity', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selleritem', to='store.category')),
                ('seller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SellerItem',
                'verbose_name_plural': 'SellerItems',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_description', models.TextField()),
                ('platform_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('customized_name', autoslug.fields.AutoSlugField(editable=False, populate_from='seller_name')),
                ('seller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
    ]
