# Generated by Django 3.2.4 on 2021-07-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210707_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='customized_name',
            field=models.SlugField(max_length=200),
        ),
    ]
